### ISSUE TITLE
How does it compare to ByteDance/Hyper-SD or sd-community/sdxl-flash ?

### ISSUE THREAD

**Issue by wodsoe** [tianweiy/DMD2#16]
How does it compare to ByteDance/Hyper-SD or sd-community/sdxl-flash ?

**Comment by tianweiy** [comment]
Result-wise, I don't have much idea. 

Method wise, Hyper-SD is orthogonal to our approach and we should be able to combine their reward optimization to further improve performance. I am not sure how sdxl-flash works.

**Comment by YoucanBaby** [comment]
> How does it compare to ByteDance/Hyper-SD or sd-community/sdxl-flash ?

I get the poor results when use Hyper-SD/DMD2 for portrait generation.
ByteDance is better in comparison.
