### ISSUE TITLE
When i train sdxl model, saving fsdp model case training stop

### ISSUE THREAD

**Issue by icelighting** [tianweiy/DMD2#25]

**Comment by icelighting** [comment]
the process hangs

**Comment by tianweiy** [comment]
thank you for the interest. Could you provide a bit more information? 

Specifically, at which line of code does the process hang? 

Here https://github.com/tianweiy/DMD2/blob/111c8bd42c5e89b9e35e8d1d5c1ca9cea3829386/main/train_sd.py#L176 

or 

https://github.com/tianweiy/DMD2/blob/111c8bd42c5e89b9e35e8d1d5c1ca9cea3829386/main/train_sd.py#L290

**Comment by icelighting** [comment]
@tianweiy On the " torch.save(feedforward_state_dict, os.path.join(output_path, f"pytorch_model.bin"))", the second place you posed. But it's solved , just turn the torch version to the requirement file.Thanks.
