### ISSUE TITLE
Is this method suits for velocity prediction? 

### ISSUE THREAD

**Issue by icelighting** [tianweiy/DMD2#27]
i don't understand  whether the score function (gradient direction) just suit for the u(t, xt)?  should i need to transfer the velocity to the u(t, xt)? as the velocity is the minus of noise and xt, 
<img width="817" alt="image" src="https://github.com/tianweiy/DMD2/assets/35771160/090a10a2-bcf5-4968-a9d9-d834451ef047">

**Comment by tianweiy** [comment]
yes, it also works for velocity prediction but you will need a set of modifications to adapt the epsilon prediction to v. 

https://github.com/tianweiy/DMD2/blob/0f8a481716539af7b2795740c9763a7d0d05b83b/main/sd_unified_model.py#L152C31-L152C48

https://github.com/tianweiy/DMD2/blob/0f8a481716539af7b2795740c9763a7d0d05b83b/main/sd_unified_model.py#L287

https://github.com/tianweiy/DMD2/blob/0f8a481716539af7b2795740c9763a7d0d05b83b/main/sd_guidance.py#L199C1-L200C1

https://github.com/tianweiy/DMD2/blob/0f8a481716539af7b2795740c9763a7d0d05b83b/main/sd_guidance.py#L231

https://github.com/tianweiy/DMD2/blob/0f8a481716539af7b2795740c9763a7d0d05b83b/main/sd_guidance.py#L295

**Comment by icelighting** [comment]
thanks for your reply, i
