### ISSUE TITLE
The arg "cls_on_clean_image"

### ISSUE THREAD

**Issue by 2862909626** [tianweiy/DMD2#30]
What is "cls_on_clean_image" do? Why are the settings different when training from scratch and resuming from a checkpoint in SD1.5?

**Comment by tianweiy** [comment]
it enables the gan loss computation. 


this is a two stage training pipeline for sd1.5 model. please refer to the description from the paper appendix 

>  Our training process involves two stages. In the first stage, we disable the GAN loss and use the AdamW optimizer with a learning rate of 1 × 10−5, a weight decay of 0.01, and beta parameters of (0.9, 0.999). The fake diffusion model is updated 10 times per generator update. We set the guidance scale for the real diffusion model to be 1.75. We use a batch size of 2048 and train the model on 64 A100 GPUs for 40K iterations. In the second stage, we enable the GAN loss with a weight of 10−3, reduce the learning rate to 5 × 10−7, and continue training for an additional 5K iterations. The total training time is approximately 26 hours.

**Comment by 2862909626** [comment]
Thank you! I have another question, you only provide the code that uses SDXL to sample images, what is the code of SD1.5 using diffusers pipeline to sample images? I tried to change the code of the one-step generation pipeline of SDXL to SD1.5, but the generated results were not good.

**Comment by tianweiy** [comment]
> the generated results were not good 

Could you show some examples. This might be the expected behavior. As we explained at https://github.com/tianweiy/DMD2/tree/main/experiments/sdv1.5 

we are training the sd 1.5 model with a guidance scale of 1.75. This one is small and both teacher and student model's output will indeed look bad. To get better looking images, we need to increase the guidance to something like 4 or above. We currently don't have the bandwidth to try this though. For aesthetic looking images, I still suggest training the SDXL model if you can

**Comment by 2862909626** [comment]
Thank you! I will try to finetune the SDXL model. If I want to finetune on a one-step generated SDXL, should I just download all the files from this link (https://huggingface.co/tianweiy/DMD2/tree/main/model/sdxl/sdxl_cond399_8node_lr5e-7_1step_diffusion1000_gan5e-3_guidance8_noinit_noode_checkpoint_model_024000) ? I noticed that the link does not include the optimizer.bin and scheduler.bin files.

**Comment by tianweiy** [comment]
we never save the optimizer / scheduler thing for sdxl models as it always give me Out of memory when I tried. But I have fine-tuned model based on just the parameter file (and reinitialized the optimizer) and this works so it should be an issue

**Comment by 2862909626** [comment]
Thanks!

**Comment by 2862909626** [comment]
When I was sampling using the SDXL one-step model, I noticed that its training resolution was 1024. I wanted to try fine-tuning the model at a lower resolution, so I performed one-step sampling at resolutions of 256 and 512 respectively. I found that when the resolution is 256, the generated results are poor, but the results are very good at 512. Does this mean that the provided model checkpoint is not suitable for further fine-tuning at lower resolutions (such as 256) ? If I want to continue fine-tuning at a resolution of 512, should I set the arg resolution to 512 during fine-tuning, or should I continue fine-tuning at a resolution of 1024 and only use a resolution of 512 during sampling?

**Comment by tianweiy** [comment]
I think the teacher model also doesn't work for 256x256 prediction as this resolution is too out of distribution for SDXL model. 

For the latter question, I am not sure but I guess you can try fine-tuning with 512x512 first as it will be much faster

**Comment by 2862909626** [comment]
When I use the command "bash experiments/sdxl/sdxl_cond399_8node_lr5e-7_1step_diffusion1000_gan5e-3_guidance8_noinit_noode.sh $CHECKPOINT_PATH $WANDB_ENTITY $WANDB_PROJECT fsdp_configs/EXP_NAME NODE_RANK_ID " to train the 1step generator, I got an error:
Traceback (most recent call last):
  File "main/train_sd.py", line 699, in <module>
    trainer = Trainer(args)
  File "main/train_sd.py", line 103, in __init__
    real_dataset = SDImageDatasetLMDB(
  File "/home/amax/Documents/zsy/DMD2-main/main/sd_image_dataset.py", line 19, in __init__
    self.latent_shape = get_array_shape_from_lmdb(self.env, "latents")
  File "/home/amax/Documents/zsy/DMD2-main/main/utils.py", line 179, in get_array_shape_from_lmdb
    image_shape = txn.get(f"{array_name}_shape".encode()).decode()
AttributeError: 'NoneType' object has no attribute 'decode'

It seems like there is a problem with the downloaded data. I have downloaded the data as "sdxl/sdxl_vae_latents_laion_500k_lmdb/data.mdb" and "pre_train/sdxl/sdxl_vae_latents_laion_500k_lmdb/lock.mdb". Did I do something wrong?

**Comment by 2862909626** [comment]
I download the data again and there is no problem know
