### ISSUE TITLE
fsdp with gradient checkpointing

### ISSUE THREAD

**Issue by LifuWang-66** [tianweiy/DMD2#32]
Hi Tianwei,

When I create an accelerate config file, it asked "Do you want to enable FSDP activation checkpointing?". I assume it meant that fsdp is compatible with gradient checkpointing. Why is it not supported in DMD2?

Thanks for your help!

**Comment by tianweiy** [comment]
this one is only a flag. we also need to modify the code to support it. Some discussions are in https://github.com/tianweiy/DMD2/issues/23#issuecomment-2195634124

However, DMD training is a little complex with different optimizers / models are updated in different frequencies and some models running in a no_grad mode. This would make implementing the correct logic for gradient accumulation a little challenging. Therefore we haven't got chance to look into this yet

**Comment by LifuWang-66** [comment]
I received the following error when running sdxl training with accelerate. 
> Traceback (most recent call last):
  File "main/train_sd.py", line 702, in <module>
    trainer.train()
  File "main/train_sd.py", line 599, in train
    self.train_one_step()
  File "main/train_sd.py", line 404, in train_one_step
    guidance_grad_norm = accelerator.clip_grad_norm_(self.model.guidance_model.parameters(), self.max_grad_norm)
  File "/root/mambaforge/envs/dmd2/lib/python3.8/site-packages/accelerate/accelerator.py", line 2115, in clip_grad_norm_
    return model.clip_grad_norm_(max_norm, norm_type)
  File "/root/mambaforge/envs/dmd2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/mambaforge/envs/dmd2/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1042, in clip_grad_norm_
    local_sharded_norm = _get_grad_norm(sharded_params, norm_type).to(
  File "/root/mambaforge/envs/dmd2/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1983, in _get_grad_norm
    raise ValueError(
ValueError: Requires uniform dtype across all gradients but got {torch.bfloat16, torch.float32}

> 

I followed your setup and commented [this line](https://github.com/tianweiy/DMD2/blob/main/main/train_sd.py#L34) out. Not sure if I have the wrong accelerate config or missing something else.

> compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: SIZE_BASED_WRAP
  fsdp_backward_prefetch_policy: NO_PREFETCH
  fsdp_forward_prefetch: false
  fsdp_min_num_params: 3000
  fsdp_offload_params: true
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
