### ISSUE TITLE
why divide by the mean of torch.abs(p_real)

### ISSUE THREAD

**Issue by PeiqinSun** [tianweiy/DMD2#46]
Hi, DMD2 is another awesome work after DMD.

https://github.com/tianweiy/DMD2/blob/main/main/sd_guidance.py#L237C1-L239C42

But, in your implement code, why divide by the mean of torch.abs(p_real)? 
in my opinion, should multi by (alpha_t / sigma_t^2)

Have any detail in your paper?

**Comment by tianweiy** [comment]
this is followed from the original dmd paper (equation 8). we found it to work comparably or slightly better than a few other alternatives (see Table 2)

**Comment by PeiqinSun** [comment]
Thanks for your reply.

**Comment by xumingw** [comment]
I am wondering if we substitude eq 8. 5. 4. into eq. 7, we get alpha*(u_fake-u_real)/mean(abs(u_base-x)), but the code have no alpha coeffiecient, why?
