### ISSUE TITLE
a Lora version to add to any Community Models?

### ISSUE THREAD

**Issue by xiaoleexiang** [tianweiy/DMD2#5]
Could a Lora containing the difference between Base XL and This SDXL (4-steps) Checkpoint successfully transfer the 4-steps inference capability to any of the finetunes of Base SD-XL?

**Comment by tianweiy** [comment]
we just released one. you can find the usage at https://huggingface.co/tianweiy/DMD2 

First time using LORA for me so could you try and let me know if the format is correct? 

Thanks

**Comment by voodoohop** [comment]
Will test later on today too applying it to a fine-tune of sdxl and report back.

**Comment by tianweiy** [comment]
I tried it with some finetuned models. It still seems to work the best with the original sdxl one :( . Probably there are some lora parameters that I haven't done right.  I also noticed that we might need to use a smaller lora_scale during inference for the finetuned model to have less artifacts. 

```python
pipe.fuse_lora(lora_scale=0.75)  
```

**Comment by tianweiy** [comment]
left is original sdxl, right is Juggernaut-X-v10

<img width="1504" alt="Screenshot 2024-05-30 at 1 52 45 PM" src="https://github.com/tianweiy/DMD2/assets/38497390/1bc04115-fd42-4b1c-8aa0-4f17772d1356">

**Comment by voodoohop** [comment]
lora_scale 0.5 seems to be working ok for me with the 4step lora and this model:

https://civitai.com/models/413466/boltning-realistic-lightning-hyper

it's currently powering the image generation on http://pollinations.ai
