### ISSUE TITLE
 Why is uncorrelated noise used in backward_simulation? 

### ISSUE THREAD

**Issue by XiaXin-Aloys** [tianweiy/DMD2#9]
[backward_simulation](https://github.com/tianweiy/DMD2/blob/main/main/sd_unified_model.py#L189)

Why is uncorrelated noise used here?  Why torch.randn_like(noise) instead of using noise directly?

**Comment by tianweiy** [comment]
I noticed that correlated noise will lead to artifacts during both test-time inference and backward simulation. 

The artifact looks like the following  
<img width="825" alt="Screenshot 2024-05-27 at 8 25 49 AM" src="https://github.com/tianweiy/DMD2/assets/38497390/e46376b7-3750-4fde-9ce7-2f81e4c9a9ed">
